[tool.poetry]
name = "api-gateway"
version = "0.1.0"
description = "A FastAPI project template managed with Poetry"
authors = ["Your Name <you@example.com>"]
license = ""
readme = "README.md"
packages = [{ include = "app" }]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.135.1"
pydantic = "^2.12.5"
python-dotenv = "^1.2.1"
uvicorn = { extras = ["standard"], version = "^0.32.0" }

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
pylint = "^3.3.1"
httpx = "^0.28.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
