[tool.poetry]
name = "api-gateway"
version = "1.0.4"
description = "A FastAPI project template managed with Poetry"
authors = ["Benjamin Harris <Benjamin@aintgivinnomailyo.com>"]
license = ""
readme = "README.md"
packages = [{ include = "app" }]

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.135.1"
pydantic = "^2.12.5"
pydantic-settings = "^2.7.1"
python-dotenv = "^1.2.1"
uvicorn = { extras = ["standard"], version = "^0.32.0" }
PyJWT = { extras = ["crypto"], version = "^2.10.0" }
httpx = "^0.28.1"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
pylint = "^3.3.1"
httpx = "^0.28.1"
pytest-asyncio = "^1.4.0"

[tool.pylint.main]
ignore-paths = ["tests/"]

[tool.pylint.messages_control]
disable = ["C0114", "C0115", "C0116"]

[tool.pylint.design]
min-public-methods = 1

[tool.pylint.format]
max-line-length = 100

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--ignore=tests/integration"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
